---
- name: Ensure the users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
    create_home: yes
  loop: "{{ users }}"

- name: Add SSH authorized keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  when: item.ssh_key is defined
  loop: "{{ users }}"