---
- name: Add Kodi Repository
  apt_repository:
    repo: ppa:team-xbmc/ppa
    state: present
  register: ppakodi
  become: yes

- name: Adding Teamviewer signing key on Debian based mediaplayer
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    state: present 

- name: Enabling Teamviewer Repository on  Debian based mediaplayer
  apt_repository:
    repo: "deb [arch=amd64] http://linux.teamviewer.com/deb stable main"
    state: present

- name: Update all installed packages using APT module
  apt:
    name: '*'
    state: latest
    update_cache: yes
    only_upgrade: yes
  register: apt_update_status

- name: Remove APT packages not needed anymore
  apt:
    autoremove: yes

- name: Install multiple packages on mediaplayer
  package:
    name:
      - xrdp
      - vlc
      - performous
      - firefox
      - software-properties-common
      - kodi
      - teamviewer
      - gcc
      - make
      - xubuntu-desktop

    state: latest
    update_cache: true