---
- name: Add host fingerprints to known_hosts using IP addresses
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get SSH fingerprints for all hosts using IP addresses
      command: "ssh-keyscan {{ hostvars[item].ansible_host | default(item) }}"
      loop: "{{ groups['all'] }}"
      register: fingerprints
      ignore_errors: yes

    - name: Add fingerprints to known_hosts file
      known_hosts:
        name: "{{ hostvars[item.item].ansible_host | default(item.item) }}"
        key: "{{ item.stdout }}"
        state: present
      loop: "{{ fingerprints.results }}"
      when: item.rc == 0
