---
- name: Install Ansible collections
  hosts: localhost
  connection: local
  roles:
    - install-ansible-collections

- name: Installing FreeIPA
  hosts: ipaserver
  become: yes
  roles:
    - install-requirements-freeipa
    - freeipa.ansible_freeipa.ipaserver