---
- name: Install required system packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: latest

- name: Install software-properties-common on Debian and Ubuntu
  package:
    name:
      - software-properties-common
    state: latest
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Ensure Python3 and pip are installed
  package:
    name:
      - python3
      - pip
    state: present
    
- name: Install Docker CE
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Install Docker Python module using pip
  command: python3 -m pip install docker

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true
    
- name: Setting up user var
  set_fact:
    username: "{{ lookup('env','USER') }}"

- name: Add current user to the Docker group
  user:
    name: "{{ username }}"
    groups: docker